import { Providers } from "../providers";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "~/styles/globals.css";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  /* eslint-disable */
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        <Toaster position="top-center"/>
      </body>
    </html>
  )
}
